Dev/jdsequeira/us vbs22 19 google maps api
VoiageTripPlanner/TripPlanner pull request #10
Opened 2024-07-18 21:41 UTC by DieS06

Se creó la entidad Location, con su respectivo Repositorio, Service y Controller, además su unit testing para verificar si el Location se está guardando en el Repositorio.

2024-07-21 03:51 UTC, mur-tz requested changes

2024-07-21 03:51 UTC, mur-tz commented on demo/src/main/java/com/project/demo/rest/LocationController.java
@DieS06 

Here, there is a couple of things you can take a look at:

1. For the Mappings, there is no need of using the "/", with the declaration of the Protocol example: @PostMapping is enough
2. Make sure you add the pertinent annotations in the methods, such as @RequestParam or @RequestBody. Take as an example the screenshots below. This was bad on my own Currency and Country controllers, so I'm fixing them soon.
![image](https://github.com/user-attachments/assets/da0857c4-d95e-47c5-b635-4fefca87c113)
![image](https://github.com/user-attachments/assets/1bb397ff-31bb-402e-9700-97d70af31e1a)

4.  If you think you won't use certain methods, feel free to not use the Interface or not expose the endpoints through mappings, this way we avoid having ghost endpoints in our app

2024-07-21 03:52 UTC, mur-tz commented on demo/src/main/java/com/project/demo/rest/LocationController.java
Sorry, for the third one I only meant the Controller one, just for the sake of no ghost endpoints, for the other classes, I don't think there is much trouble on having methods that only return null, since no endpoint will call these "ghost" methods.

For the others, I like the changes 💯

2024-07-22 03:52 UTC, DieS06 commented on demo/src/main/java/com/project/demo/rest/LocationController.java
Already solved all comments, thanks for the feedback.

2024-07-22 21:20 UTC, nefi-cenfo approved these changes

2024-07-23 00:31 UTC, mur-tz approved these changes

2024-07-23 00:31 UTC, merged