Dev/iwu/vbs22 74 recomendar vestimenta
VoiageTripPlanner/TripPlanner pull request #27
Opened 2024-07-28 19:46 UTC by ichivancrCenfotec

Added controllers to Open AI

2024-07-28 23:13 UTC, DieS06 requested changes

2024-07-28 23:13 UTC, DieS06 commented on demo/src/main/java/com/project/demo/entity/Place.java
> +    private long latitude;
Use Location object that has address, latitude, longitude and placeId.

2024-07-29 01:12 UTC, mur-tz approved these changes

2024-07-29 02:00 UTC, nefi-cenfo approved these changes

2024-07-29 02:02 UTC, DieS06 approved these changes

2024-07-29 04:06 UTC, nefi-cenfo approved these changes

2024-07-29 04:16 UTC, merged